# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: innovation-scoreboard
      POSTGRES_USERNAME: innovation-scoreboard
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:7.2.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
