# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: dev
    volumes:
       - ./:/code
    working_dir: /code
    command: ["mvn -B spring-boot:run"]
    depends_on:
      - postgres
      - elasticsearch
    tty: true
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ELASTICSEARCH_SCHEME: ${ELASTICSEARCH_SCHEME}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH_NAMESPACE_PREFIX: ${ELASTICSEARCH_NAMESPACE_PREFIX}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      SECURITY_ALLOWED_ORIGINS: ${SECURITY_ALLOWED_ORIGINS}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      LOG_APPLICATION_NAME: ${LOG_APPLICATION_NAME}
      KEYCLOAK_SSL_REQUIRED: ${KEYCLOAK_SSL_REQUIRED}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - internal
      - authentication

  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: innovation-scoreboard
      POSTGRES_USERNAME: innovation-scoreboard
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - internal

  elasticsearch:
    image: elasticsearch:7.2.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - internal

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    networks:
      - internal

networks:
  authentication:
    external: true
  internal:
    external: false
