services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ELASTICSEARCH_SCHEME: ${ELASTICSEARCH_SCHEME}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH_NAMESPACE_PREFIX: ${ELASTICSEARCH_NAMESPACE_PREFIX}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      SECURITY_ALLOWED_ORIGINS: ${SECURITY_ALLOWED_ORIGINS}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_SSL_REQUIRED: ${KEYCLOAK_SSL_REQUIRED}
      LOG_APPLICATION_NAME: ${LOG_APPLICATION_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
